apiVersion: v1
kind: Namespace
metadata:
  name: gopaas
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gopaas-config
  namespace: gopaas
data:
  CONSUL_ADDRS: "consul.gopaas.svc.cluster.local:8500"
  GOPAAS_MODE: "k8s"
  KUBE_NAMESPACE: "default"
  RATE_LIMIT_QPS: "50"
